version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./.env:/var/www/html/.env
      - /c/Users/ikul2/Desktop/GitHub/Frontend/First_PHP:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: composer install
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
