version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - composer-vendor:/var/www/html/vendor
      - ./logs:/var/www/html/logs
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

volumes:
  composer-vendor:
